feat: add webpack support for devtool sourcemap options
pixeloven/pixeloven pull request #275
Opened 2020-09-30 19:15 UTC by vp737

enabled and SourceMapDevToolPlugin
https://webpack.js.org/plugins/source-map-dev-tool-plugin/

2020-10-02 00:24 UTC, vp737 commented
@ductiletoaster @jimmynotjim PR open for review

2020-10-07 17:11 UTC, ductiletoaster requested changes

2020-10-07 18:08 UTC, vp737 commented on packages/pixeloven-webpack/config/src/types.ts
> +    sourceMap: string;
Updated to type `boolean | string` https://github.com/pixeloven/pixeloven/pull/275/commits/1f3a0e7f65ffd230281011fb64f5251b293b9d8f

2020-10-07 18:08 UTC, vp737 commented on packages/pixeloven-webpack/compiler/src/index.ts
> +    sourceMap: "eval-source-map",
Updated default to `false` https://github.com/pixeloven/pixeloven/pull/275/commits/1f3a0e7f65ffd230281011fb64f5251b293b9d8f

2020-10-07 19:24 UTC, ductiletoaster approved these changes

2020-10-07 19:57 UTC, merged